### ISSUE TITLE
Marking Custom Page in Navigation as Active

### ISSUE THREAD

**Issue by Alundran** [e107inc/e107#1604]
Hi,

I might be totally missing something here but the only time when I can see the site link I click on as 'active' is when I create the site link to point to page.php. If I use (for example) page.php?8 to point to a different page, that isn't marked as active when I click on the link in the navigation bar. If I have a site link with page.php AND I use page.php?8, when I click on the page to go to page 8 it shows whatever link I set as page.php as the active one even though I'm not in there.

I'm not sure if I'm explaining myself, here are steps to replicate:

1. Create a new page and note the ID number
2. Go to Site Links
3. Add a Site Link that points to page.php?idNum (example page.php?8)
4. Go to the main site and click on that link - note that it isn't set as active
5. Go back to Site Links and add a link that points to page.php
6. Go to the main site and click on the page with page.php?idNum and note that it sets whatever link is set as page.php as active

In the e107 demo site, it has 'Content' with page.php then sub-menus which works so I'm not sure if that's 'how' it should be used (this wouldn't work for me in my situation).

Thanks

**Comment by rica-carv** [comment]
Currently even the standard page url is not marked as active on the links....
If i remember correctly, this has already been solved previously.....

**Comment by Moc** [comment]
It may very well be that this issue is resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in Preferences > Advanced features
- Go to Tools > Database > Sync with Github 

Alternatively you can download the ZIP file with all the latest files included by hitting the 'Download ZIP' button at the top of this page: https://github.com/e107inc/e107

**Comment by rica-carv** [comment]
@Moc I got always the latest update, and i can confirm this issue is still active.....

**Comment by Alundran** [comment]
Thanks All - tested with the latest GitHub and same issue as rica-carv said above.

Thanks

**Comment by Moc** [comment]
Is this issue still occurring?

**Comment by Moc** [comment]
@Alundran @rica-carv Is this issue still occuring?

**Comment by rica-carv** [comment]
@Moc I can confirm, issue still persists....
![teste_-_selos_portugal_-_2018-06-25_19 39 21](https://user-images.githubusercontent.com/17130530/41869151-01bd12d0-78b0-11e8-8da0-49cffb5ef02d.png)
