### ISSUE TITLE
Forum templates wrappers not working?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2023]
I've tryed severall` forum_template.php` shortcodes wrappers variations, but it seems they don't work:
```
$FORUM_TEMPLATE_WRAPPER['THREADSX'] = "==={---}===";

$SC_WRAPPER['THREADSX'] = "==={---}===";

$FORUM_TEMPLATE_WRAPPER['main']['forum']['THREADSX'] = "==={---}===";
```

Anyone has this same issue?

**Comment by CaMer0n** [comment]
Enable Debug Mode : "Bbcode + Shortcodes" - Can you find a wrapper in the list? (in the footer)

**Comment by rica-carv** [comment]
No, there's no wrapper in the list.
More weird is that i know that on another page (`forum_viewforum`) there's a wrapper (for `viewable_by` shortcode), and also when debugging it there's no wrapper listed....
Real weird...

**Comment by CaMer0n** [comment]
I have added some for the main forum page. (I believe thisscript  is using your upgraded code you submitted) 
Please try with my changes and see how it goes now. Keep in mind that if there is no shortcode in the template, it won't display in the list.  
eg. If you look at the 'track' page with DEBUG enabled, you won't find `forum/track/end` in the list of wrappers, because `$FORUM_TEMPLATE['track']['end']`  does NOT contain any shortcodes, therefor the shortcode handler is never called.

**Comment by rica-carv** [comment]
@CaMer0n Sorry, but with your changes it still doesn't works....

**Comment by CaMer0n** [comment]
Should be fixed now. 
For v2.x shortcode wrappers to function correctly, the template files also need to be loaded in the v2.x fashion using e107::getTemplate();  ie. require/include will fail to handle the v2.x wrapper format.

**Comment by CaMer0n** [comment]
Closing this, but please re-open if necessary.

**Comment by rica-carv** [comment]
Well, it seems this issue is back again, since i can only add wrappers in legacy format: `$SC_WRAPPER['THREADSX'] = "==={---}===";`
