### ISSUE TITLE
New menu manager doesn't render menu areas

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2331]
New menu manager doesn't render menu areas:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/22386395/cb857200-e4ce-11e6-8dda-8b3219ae7d3f.jpg)

Theme layout code:
```
$LAYOUT['jumbotron_full_sidebar_right'] =  <<<TMPL
  <!-- Main jumbotron for a primary marketing message or call to action -->

    <div class="no-overflow">
        <div class="row max-height">
            <div class="span8 scrollable">
    <div class="container">
  <div class="container">
     {ALERTS}
  </div><!-- /.container -->

    {SETSTYLE=jumbotron}

	{WMESSAGE=force}   

	{SETSTYLE=default}

	{---}
	
</div><!-- /.container -->
                </div><!-- /.span8 -->
            <div class="span4 scrollable">
    <div class="container">
      <!-- Example row of columns -->
      <div class="row panel-group">
{SETSTYLE=menu}
{TCOREMENU}
{MENU=1}
        </div><!-- /.row -->
      <div class="row panel-group" id="accordion">
{SETSTYLE=menu}
{MENU=2}
        </div><!-- /.row -->
      </div><!-- /.container -->
            </div><!-- /.span4 -->

</div><!-- /.row .max-height-->
</div> <!-- /.no-overflow -->
TMPL;
```

**Comment by mcpeace-maw** [comment]
I've noticed this problem too. I think the theme style.css file is not loaded into the iframe. 
But is not just that.
If you look Menu Manager page on a screen under 1200px wide, the page has no scrollbar and the bottom of the page can not be seen. Also dropdown menu who displays areas where to activate menus don't call a scrollbar if have more buttons in it and his height is bigger than the visible area.

**Comment by CaMer0n** [comment]
I've noticed problems when the browser cache has not been updated. Other than that, I haven't. 
Also @rica-carv I tried your $LAYOUT by adding it to bootstrap3, and it renders without any problems. 

![screen shot 2017-01-27 at 16 23 19-fullpage](https://cloud.githubusercontent.com/assets/2825679/22392428/e2ed80de-e4ad-11e6-911e-a871435bc351.png)

**Comment by mcpeace-maw** [comment]
I have used FF, Chrome and IE and is the same, even with cleared cache style.css of the theme seams to not be loaded. I did a test = I have removed the loading link for bootstrap css from theme.php and added at the beginning of style.css of the theme @import for bootstrap css  and the result is like in @rica-carv image so I think style.css is not loaded in iframe.
Also if you see the page at 992px wide or less, the iframe is at the bottom of the page under left column (with inactive menus), the page don't have a scrollbar and you can see the iframe. If you click on "go" button and the dropdown menus opened have many buttons, the dropdown menus don't have a scrollbar and the buttons at the bottom remain out of visual field and can't be used. I have this behavior on 3 sites, 1 local and 2 online.

**Comment by CaMer0n** [comment]
So normally , neither of these should be working for me. hmmm.. 

![media-manager](https://cloud.githubusercontent.com/assets/2825679/22397976/fbae5640-e532-11e6-890c-79d5b89350eb.jpg)

![media-manager-2](https://cloud.githubusercontent.com/assets/2825679/22397978/00bd8a70-e533-11e6-9e11-8b7a9c3b45fa.jpg)

**Comment by mcpeace-maw** [comment]
On Menu Manager page I checked the source and I can't find the loading link for style.css and if a add the link in theme.php: e107::css('theme','style.css'); all is OK on iframe, the theme is rendered correctly on Menu Manager iframe. I know style.css suppose to be loaded by header_default, on front end is loaded but here on Menu Manager is not loaded. Any ideas what can be the source of this issue?

**Comment by CaMer0n** [comment]
I saw that too, but I need a copy of the theme to see what is going on. It could be theme.xml or something else. Please check your gitter PMs

**Comment by mcpeace-maw** [comment]
OK.

**Comment by CaMer0n** [comment]
@mcpeace-maw Please resave your theme prefs and it should be working for you.

**Comment by rica-carv** [comment]
@CaMer0n Latest github of today, still having this issue....
My theme is a modified copy of bootstrap3 core theme, and i simply can't figure out what's wrong....

**Comment by LaocheXe** [comment]
Very odd, I have a theme that is modified version of bootstrap 3 theme (but haven't updated the main core code of the them since last summer) and my menu manager area seems fine. - I will update the main core code of the bootstrap theme and see if its new code or not.

**Comment by LaocheXe** [comment]
Updated the code, every thing looks good on my end

![capture](https://cloud.githubusercontent.com/assets/5818022/22535778/e5789960-e8c2-11e6-94ac-08743653db6d.PNG)

**Comment by rica-carv** [comment]
Solved.
Thanks @CaMer0n for pointing the right direction...
