### ISSUE TITLE
YouTube video problem

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3080]
Hi Guys!

So, when I writing a news post or editing a custom page, and I want insert to a youtube video in the text body, I using Media Manager Video. I paste the youtube video code into the manager, and I choose the video and put it to the text body.
The problem is, when put it to the text body, after the video, it leaves out a large blank space, like this: http://www.kephost.com/images/2018/03/19/image03.jpg
Or this: http://www.kephost.com/images/2018/03/19/image-01-5.jpg

When I want to insert more than one video, and after the first video using "shift enter" to the line break (in edit mode: http://www.kephost.com/images/2018/03/19/image02.jpg),  the videos merge with each other, like this: http://www.kephost.com/images/2018/03/19/image01.jpg

**Comment by tgtje** [comment]
Done some testing, partial replicate. explain:
When adding a single movie (yt) no issue.
Using shift enter seems to NOT close the div (aka 'viewportal')
Now after each added movie i hit the return button instead of shift enter and a larger space in editor appears (mind i use View> Show blocks for aid). I make sure each movie is in a block, and space below..
SO yes it works, but a little bit strange, i can let them merge/seperate/larger between space etc.. (all points t div use/close/end ??)

**Comment by SimSync** [comment]
@KiraTheUltimate Could you please verify, that this issue still persists? The TinyMCE Editor has been updated in the meantime and maybe this has also fixed this issue...?!?

**Comment by KiraTheUltimate** [comment]
It's still a problem... when I paste a youtube video from the media manager, after the video the system put a big white area. ---> http://kepkuldes.com/images/915714b51b0eddf9af8a8745b4465be6.jpg
