### ISSUE TITLE
Gray thumb using mediamanager from Tinymce

### ISSUE THREAD

**Issue by albersmc** [e107inc/e107#3486]
Hello, i have a v2.1.9 e107 fresh installed in my domain, added the old backup, but whenever i upload a file from mediamanager in the Tinymce editor of the news panel, the image appear as a gray thumb, and in the frontend, appear the 300x300 gray image.
As mentioned above, an image:
<img width="516" alt="screen shot 2018-10-02 at 13 19 29" src="https://user-images.githubusercontent.com/4977279/46348594-c5ea9000-c64f-11e8-856c-97046fc4229b.png">

What could be the problem?
Thanks

**Comment by Moc** [comment]
I think this is a bug which has been fixed on Github. It will be part of the next release or you can update using the files from Github now (development verson, so bugs may be present).

**Comment by albersmc** [comment]
I have already synced with github, but the issue is still present.

**Comment by CaMer0n** [comment]
@albersmc I'd be happy to take a closer look at your issue if you would like. You can reach me in real-time on https://gitter.im/e107inc/e107

**Comment by CaMer0n** [comment]
Traced to spaces in the file-name.
