### ISSUE TITLE
Script tags are not working in TinyMCE

### ISSUE THREAD

**Issue by 2548ir** [e107inc/e107#4346]
This feature does not work with the latest e107git version and php v7.4

Example code:
`<script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script>`

**Comment by CaMer0n** [comment]
@realmontazeri Please check your settings. 

![image](https://user-images.githubusercontent.com/2825679/104813915-e8712a80-57c0-11eb-9a48-53f180d80836.png)

**Comment by realmontazeri** [comment]
@CaMer0n The value is set on default(admin) in my panel and I tried to change that to main admin but the issue is still exist.

**Comment by realmontazeri** [comment]
I am not sure if the following code solve the problem or not:
```
   context.Services.Configure<TinyMceConfiguration>(config =>
            {
                config.Default()
                    
                    .AddSetting("valid_children", "+body[style]").AddSetting("extended_valid_elements", "script[language|type|src]");
            });
```

**Comment by Jimmi08** [comment]
@CaMer0n Confirmed, but not sure if it is TinyMCE problem because data were sent correctly
![image](https://user-images.githubusercontent.com/5429548/104820496-3889d480-5835-11eb-9957-d11e5e062e40.png)

Result in DB:
![image](https://user-images.githubusercontent.com/5429548/104820509-5a835700-5835-11eb-9003-58f7d14c663e.png)

**Comment by CaMer0n** [comment]
Unfortunately, I am still unable to reproduce this issue. 

From my database: 

```
[html]<p>
<script type=&quot;text/javascript&quot; src=&quot;https://cdn.ywxi.net/js/1.js&quot; async=&quot;&quot;></script>
</p>[/html]
```

**Comment by CaMer0n** [comment]
@realmontazeri This *should* be fixed now, but please re-open if the problem continues.

**Comment by realmontazeri** [comment]
This is still an issue:
![Screenshot1](https://user-images.githubusercontent.com/10089685/107109076-5786ef80-6852-11eb-9fcf-77356223105d.png)
![Screenshot2](https://user-images.githubusercontent.com/10089685/107109077-59e94980-6852-11eb-84b8-1df4e2fbb6c6.png)

**Comment by realmontazeri** [comment]
@CaMer0n I couldn't find any option or button to re-open the issue
![Screenshot1](https://user-images.githubusercontent.com/10089685/107109076-5786ef80-6852-11eb-9fcf-77356223105d.png)
![Screenshot2](https://user-images.githubusercontent.com/10089685/107109077-59e94980-6852-11eb-84b8-1df4e2fbb6c6.png)

**Comment by CaMer0n** [comment]
@realmontazeri Is the js meant to output some html ? 

There is a known bug with the "Preview" as it should remove those [html] bbcodes.

**Comment by realmontazeri** [comment]
@CaMer0n Those html tags are not supposed to be shown in preview, they were added automatically after using script tags.

**Comment by CaMer0n** [comment]
Note to self: https://stackoverflow.com/questions/30483218/change-content-before-preview-in-tinymce-4

**Comment by 2548ir** [comment]
The issue is still exist and It is very important sometimes to use scripts in menu/pages.

**Comment by Jimmi08** [comment]
> The issue is still exist and It is very important sometimes to use scripts in menu/pages.

I can't see script tag in allowed tags for tinymce
```
		$allowedTags = array('html', 'body','div', 'a', 'img', 'table', 'thead', 'tbody', 'tr', 'td', 'th', 'b',
			'i', 'pre', 'code', 'strong', 'u', 'em', 'ul', 'ol', 'li',  'h2', 'h3', 'h4', 'h5', 'h6', 'p',
			'blockquote', /*'audio', 'video',*/ 'br', 'small'
		);
```
Can you give them example why you need this? script from your image above you should put in meta tags, not in wysiwyg area.

**Comment by 2548ir** [comment]
Putting trust seals in an specific area is one of those examples, solution please.

**Comment by Jimmi08** [comment]
@2548ir if it is for me, you should mention me. I am sorry, but I don't fully understand what you are saying. Here is the place where to insert javascript. Former metas, now meta and custom tags. 

![image](https://user-images.githubusercontent.com/5429548/131327489-c870cd4d-f858-4d8f-a5cc-2b3659a145a4.png)

**Comment by 2548ir** [comment]
> @2548ir if it is for me, you should mention me. I am sorry, but I don't fully understand what you are saying. Here is the place where to insert javascript. Former metas, now meta and custom tags.
> 
> ![image](https://user-images.githubusercontent.com/5429548/131327489-c870cd4d-f858-4d8f-a5cc-2b3659a145a4.png)

@Jimmi08 my question was so simple and clear, the solution you have mentioned in the picture is not something optional, it just insert contents of script in header or footer so lets get back to my previous post (Putting trust seals in an specific area is one of those examples).

**Comment by 2548ir** [comment]
The only solution for this issue is to attach a link with contents which are imported in wysiwyg area so the scripts like this: ` <script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script>` can be executed behind a picture as a link inside wysiwyg but first have to validate its link by executing the script outside TinyMCE.
