### ISSUE TITLE
PHP 8 sign up

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#4424]
## Bug Description
Using php 8 signup throws error on array_merge

## How to Reproduce
1. Click sign up
2. Advance (when coppa is enabled)
3. Enter details

## Expected Behavior
Normal signup should be possible
## Server Information
MySQL
10.3.24-MariaDB-cll-lve
Database: xxxxxxxxx_testdbase
PDO: Enabled
Mode: NO_ENGINE_SUBSTITUTION (live)
PHP Versie
7.4.10

MySQL
10.4.17-MariaDB
Database: vstoresite
PDO: Aan
Mode: NO_ENGINE_SUBSTITUTION (local)
Php Versie
8.0.1
### PHP Operating System
Tested on php 7.3.22 OK (live) (same server switching to >
Tested on php 7.4.10 OK (live)
Tested on php 8.0.1 (only local available)
```

Linux XXXXXXXXXl 3.10.0-962.3.2.lve1.5.38.el7.x86_64 #1 SMP Thu Jun 18 05:28:41 EDT 2020 x86_64 (live)
--

Windows NT DESKTOP-XXXXXXX 10.0 build 19042 (Windows 10) AMD64 (local)
--





```

### PHP Modules
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
zip
zlib  (live)

apache2handler
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib  (local)

## Additional Information
Trying to signup getting following error:Fatal error: Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in R:\Xamp801\htdocs\vstore\signup.php:585 Stack trace: #0 R:\Xamp801\htdocs\vstore\signup.php(585): array_merge(Array, NULL) #1 {main} thrown in R:\Xamp801\htdocs\vstore\signup.php on line 585

However !! Data (user signup) is correctly stored in Members area
Latest Git version, new install of e107

**Comment by CaMer0n** [comment]
@tgtje This commit should fix it. Please re-open if necessary.

**Comment by tgtje** [comment]
Helas it (for me) does not solve it. Ican not re-open it seems.
Overall the error changes to the previous line 584 now instead of 585
Fatal error: Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in R:\Xamp801\htdocs\e107\signup.php:584 Stack trace: #0 R:\Xamp801\htdocs\e107\signup.php(584): array_merge(Array, NULL) #1 {main} thrown in R:\Xamp801\htdocs\e107\signup.php on line 584.

Deeper investigation leads to setting in user registration coupled to NO Verification. When this is set, the error occurs.
Using Email verif. or Admin approval > NO errors and all functions.
Tested and ONLY happens on the php 8 install (local) Live 7.4.10 has no issues with it. Maybe this helps?

**Comment by tgtje** [comment]
Issue no longer exists on fresh installment (php 8.0.3).
So i think this can be closed as a e107 bug as guest signup functions now .

(a related issue  for this is in plugin (vstore) but is posted there).

(Please do not get confused by domain name vstore posted in issue report as this was a different installment-name and version )
