### ISSUE TITLE
Theme Help

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#870]
I copy bootstrap 3 theme folder, renamed it and change the name in the xml - went and applied it to site theme and when I go to check it out it becomes a blank page.

Also I want to make is so the SITEIMAGE (logo) is shown instead of the SITENAME for the navbar area. I am trying this:

if (SITEIMAGE)
thing with SITEIMAGE
else
thing with SITENAME

idk if my IF statement is correct and/or if SITEIMAGE is still being used or not, I check the dev info on e107.org but nothing about SITEIMAGE.

**Comment by LaocheXe** [comment]
So SITEIMAGE is SITELOGO (got it showing)

right now this is what I have
if(SITELOGO != null)
{
$LAYOUT['_header_'] = '
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{SITEURL}">{SITELOGO}</a>
}
else
{
$LAYOUT['_header_'] = '
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{SITEURL}">{SITENAME}</a>
}

issue is, if no SITELOGO is selected then by default it uses the e107 logo - is my IF statement correct?

**Comment by CaMer0n** [comment]
If I understand well, you would like to fallback to the SITENAME if SITELOGO is empty, correct?

**Comment by LaocheXe** [comment]
Yes

**Comment by CaMer0n** [comment]
I would suggest creating a new shortcode in theme_shortcodes with the following: 
     
    if(empty(SITELOGO))
    {
       return e107::getParser()->parseTemplate("{SITENAME}",true); 
    }

But I may add something to support that.. so you could just do this: 

    {SITELOGO: fallback=SITENAME}

**Comment by CaMer0n** [comment]
Done, but not tested. Please give it a try.

**Comment by LaocheXe** [comment]
So I tried the {SITELOGO: fallback=SITENAME} and went to pref to select None for the site logo and still get the default e107 logo.

if(empty(SITELOGO))
{
   return e107::getParser()->parseTemplate("{SITENAME}",true); 
}

I get an error with the IF statement.

**Comment by LaocheXe** [comment]
Now I feel like a dummy, I got it working - forgot the {}

Now the issue is - it still shows the Default e107 Logo

**Comment by CaMer0n** [comment]
Make sure it is as follows: (note the lowercase)
   
    {SITELOGO: fallback=sitename}

**Comment by LaocheXe** [comment]
That works, I had it caps - now the issue lays in the css I think, not to sure - http://throwbackgaming.cu.cc/ (my testing site)

With no image selected you get the site name but not using the css style format for it as you can see on the site atm
